/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wtycbakrjjyvfjscdpdw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0eWNiYWtyamp5dmZqc2NkcGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2OTQ1NjksImV4cCI6MjA3ODI3MDU2OX0.4zf52QMCIyh6CqlCMpBYNA-x2sv6O-NuhyIIEXgh-i0"